spring:
  redis:
    host: 47.102.202.189
    password:
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboothotel?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: 12345678
  sql:
    init:
      mode: never
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: ./data/temp
  mail:
    host: ## 邮箱域名,QQ邮箱为smtp.qq.com,其他自行baidu或者google ##
    username: ## 邮箱名 ##
    password: ## 服务密码 ##
    senderName: 防疫酒店管控系统-1
email-group:
  configs:
    mail-0:
      host: smtp.qq.com
      username: 302920276@qq.com
      password: twgyskxatdgucbdi
      senderName: 防疫酒店管控系统-1
    mail-1:
      host: ## 邮箱域名,QQ邮箱为smtp.qq.com,其他自行baidu或者google ##
      username: ## 邮箱名 ##
      password: ## 服务密码 ##
      senderName: 防疫酒店管控系统-2



mybatis-plus:
  configuration:
    # 驼峰
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 未删除
      logic-not-delete-value: 0
      # 删除
      logic-delete-value: 1
      # id类型
      id-type: id_worker_str

# token配置
jwt:
  # 令牌自定义标识
  header: Authorization
  # 令牌秘钥
  secret: 12d8sxsm+xswxyy+2d8sxswxyybmaik/2dwzmztbdwtb/3rggdxfnjppspaparggdxfnjppspapapa+hbgwjybqyl+++++
  # 令牌有效期（默认30分钟）
  expireTime: 7200000
  token-prefix: Bearer
  iss: tomato
  roleClaims: rol
server:
  port: 8080
  tomcat:
    basedir: ./data/temp

qiniuyun:
  ak: lb5PC64hS-6tcINgYqIBDvzbIIHVlr0CZ7lM70bT
  sk: JlMQ4hFserulVHnXVK2kGq64ZChvERYxNTfBMQ0e
  bucket: graduationblog
  domain: image.educy.top

alipay:
  appId: 2016091300504379
  gateway: https://openapi.alipaydev.com/gateway.do
  privateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC1OQBO5rgfy+gGLHXfG3o68ZWGqRUhFAgtu0IJwTLk0DBH5tF2kzBJIe4shGW90eb0KUeiSkTKiaflzmj3DrxIuDODtYDijdsyQWJUU60HoiebMTkujDR19OWBZ8M8wOQY6LvSsxmh2Y6A27rUtgHhyAR5zapamEzFPipEemUudEQ3pJbBoD5HPgPbfF2XJfKnlKQZs20vWqn1NoKlVgFUjBGJUAgblX6GimDvDySoTuHotutekii54pWAFoFIspWJWE7m/V97V+MWOaftMrVQJFt5RoGawJ7xyD+wvL9A7PwV+C3yTTraGV4bqc1Tjf9DUC5GGtvKFKs8J53ksDNBAgMBAAECggEBAKQsJm5UL5uGkwT8xC/BacL6VrZueNjFl/8t9E53+s41GHgaz8l24Dhwh59GthD3lh29Q8rvM1C00iirDIY8kC/kx65bAI69akUl3Jl+UHNo4C6EskPL+j6eBEhuIv3n1PwH4xem7uKj/6gW5zOKSzwqgnuB6QE3ldzeS1ZL91vTqm1hpA13OIzwsCYQC9tldGqJ5zFXg5w8Eo80xDp7KZkfz9jLuGGZc34uKxXyW4FXdzPGS/s9NFuwEvcYygfI14ndB8wrQscV8k69EBl57sHcpBP9fMO6J3AAd0A5gN7FRayQNcx0ATxcl+gz0qYqCIubRlVmcDWr7y1q+nE9NB0CgYEA7O0tXEy6y1wx2azZhhdNEE5M7tCDWcTsrlPziqZhMlyHuY+jX3IvkhErPt8tQhrXHwLz2mTx9WYw5Gx1kLuekbW0YTNdLacxkh9Ue2wa1vB3pGPoKhMBaOpsw9cOBLODrbVpqYz3zoLou7MFQZCH96vvcO6cc/y5IaKn62Vay9sCgYEAw8/SrC+f+vT6CqaKK2x4/kopTDV5pkQjJIf3fe0DTfyTwJMGDT9kPMF116+k0ph+TwcliZsgROGKMTHLqljZW/Q355uug7xI38vlSWICQsfi8zs4UQxw1ET1B0NVQLGG5qJh2DqI8D5PrKVhg6a3rg+r06cdCVmm+WwPRkS+1hMCgYEAmFXfZotHR14eB1GmAxuURzmxKZQUAHIno+cCnlFgCVuJQPxkFQh8IbS8U453sRtE2gGx/OgO0rREF3rNFKQtzo5ATocSEDqCGuveDAV0NGMk6iP6sKLLs0OXb0wlDUzHC7erGoMzCisNrTHr3T4qzkpUiA5Dtif2ePP2d9oRSSUCgYEAvoFmNRGMsys+TbhjuwWo3bYnYbaxKRsnmbYTCtfaHDi9Q2GHRMJE8ntB/Fstn5qvYJHSaoObLIjF20DYJl6U8kqzTUmAyzgXKm0EIZYSHwi7++rEys2wxERmo+9VdUCCv8aCLU4dxqbI+25XZi+Aiv9CLARtUph/xDDm13WwuTMCgYAseLlZ6arMkwbE+tWlHeVB02jRhPKdXkZ/XdeZqZWq9cyWKggH/L7mKpY0h8NSEVv8tLcZ01p0JzZnBfAHIiqsC6HoH1Tz9Qqmzlg6TStnI8QiiNToJThQSzqWj4sm81j+0sR4oiUKcHGg762Q/g+8p7iJTh3bH2qUUpK55JJG/Q==
  format: json
  charset: utf-8
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp2vE/iQ01uIH+IyML07iARpglpWuJUIsQZAesj8vh0MXxTBzOSrMUCndrA8lrSoY61Jni921K3jH8gH0p9iGZlFbm8uSAsXnHH1jhLWgSAxzBa2+wiAJ3A0v2CIypONSmzrdtgUBD6A4PMwJOBN1H73U7GUVQpctobM3sVJ9AtWnuxMls/9Naox/I3ANGzZlTPxFvxxQjBwUSXI8nY8rjJOXjdb3CFurMMP/dV7I23tyaFFUQeKICJNWMKzDILJ7xntvkwM20zY8dwSiYISc1waU4BAIHJcDtvQsY/d3zaWviLCk+pFy7j9qhM2N4rr+M7He4Cbd7nqaz1O2F86adQIDAQAB
  signType: RSA2



